### ISSUE TITLE
Compile Error.

### ISSUE THREAD

**Issue by xamox** [kikohs/freak#1]
Trying to compile on Ubuntu 12.04. I have manually built and installed OpenCV 2.4.  Using Cmake 2.8.7.

I get the following error:

xamox@xamox-desktop:~/Code/freak/build$ cmake -DCMAKE_INSTALL_PREFIX=/home/xamox/Code/freak/ -DOpenCV_DIR=/home/xamox/Code/OpenCV-2.4.0/ ..
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xamox/Code/freak/build
xamox@xamox-desktop:~/Code/freak/build$ make claen
make: **\* No rule to make target `claen'.  Stop.
xamox@xamox-desktop:~/Code/freak/build$ make clean
xamox@xamox-desktop:~/Code/freak/build$ make
[ 33%] Building CXX object src/CMakeFiles/freak.dir/freak.cpp.o
/home/xamox/Code/freak/src/freak.cpp: In member function ‘void cv::FreakDescriptorExtractor::buildPattern(const string&)’:
/home/xamox/Code/freak/src/freak.cpp:200:9: error: ‘memcpy’ is not a member of ‘std’
/home/xamox/Code/freak/src/freak.cpp:200:9: note: suggested alternative:
/usr/include/string.h:44:14: note:   ‘memcpy’
make[2]: **\* [src/CMakeFiles/freak.dir/freak.cpp.o] Error 1
make[1]: **\* [src/CMakeFiles/freak.dir/all] Error 2
make: **\* [all] Error 2

**Comment by kikohs** [comment]
fixed.

**Comment by xamox** [comment]
Awesome, thanks!
